# Generated by Django 5.1 on 2025-01-12 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='splitwise.events')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='splitwise.events')),
                ('creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_expenses', to='splitwise.users')),
                ('members', models.ManyToManyField(related_name='participated_expenses', to='splitwise.users')),
            ],
        ),
        migrations.CreateModel(
            name='Debts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='splitwise.events')),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='splitwise.expenses')),
                ('debtor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='splitwise.users')),
                ('payer_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='debts_creator', to='splitwise.users')),
            ],
        ),
    ]
