# Generated by Django 5.1 on 2025-01-06 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debtor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='splitwise.users')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='splitwise.events')),
                ('payer_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='debts_creator', to='splitwise.users')),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='splitwise.expenses')),
            ],
        ),
    ]
