# Generated by Django 5.1 on 2024-08-28 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise', '0004_alter_events_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_expenses', to='splitwise.users'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='members',
            field=models.ManyToManyField(related_name='participated_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='splitwise.events'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
