# Generated by Django 5.1 on 2024-09-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise', '0005_expenses_creator_expenses_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='members',
            field=models.ManyToManyField(related_name='participated_expenses', to='splitwise.users'),
        ),
    ]
