[tool.black]
line-length = 100

[tool.flake8]
import-order-style = "google"
application-import-names = ["about", "catalog", "core", "homepage", "lyceum"]
known-third-party = ["django"]
ignore = ["I100", "I101", "I201"]
inline-quotes = "double"
